[package]
name = "PawLang"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8.1"
pest_derive = "2.8.1"
thiserror = "2.0.16"
anyhow = "1"

cranelift-codegen  = "0.123.2"
cranelift-module   = "0.123.2"
cranelift-object   = "0.123.2"
cranelift-frontend = "0.123.2"
target-lexicon     = "0.13.2"
